### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by sec13b** [7Elements/Fortigate#2]
ile "/usr/local/lib/python3.11/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

**Comment by LukeLauterbach** [comment]
In case anyone runs into this in the future, this is typically caused by an outdated version of pyOpenSSL. A quick fix is `pip install pyopenssl --upgrade`.
